### ISSUE TITLE
Update  ReadMe

### ISSUE THREAD

**Issue by gpassarelli** [deefour/transformer#1]
Update the ReadMe file to reflect the changes on commits that changed the way we should use the methods to transform the attributes.

The commits are:
# 12fcc8699fe9d5e23f74ada263cf0020dc237085
# 5b70ab7ce3aa0d1d5798be0be309aa00a2a5f918

**Comment by deefour** [comment]
Thanks. This wasn't documented because I had been playing with the change from `@ignore` to `@attribute` but wasn't completely happy with the implementation.

I've tagged [`1.3.0`](https://github.com/deefour/transformer/tree/1.3.0) which relies on `@attribute` annotations **only on methods that aren't camel-cased versions of attributes that exist on the source data.** 

I am happy with this because:
- I don't care for having `@ignore` all over this library's methods.
- I think it's redundant to tag methods with `@attribute` that clearly are transforms for source data.
- I don't like the idea of abandoning annotations altogether for some `get[AttributeNameHere]Attribute` method naming convention.

https://github.com/deefour/transformer/tree/master#method-attributes
